# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HW2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(348, 720)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 300, 80))
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(25, 30, 250, 30))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 120, 300, 130))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(25, 30, 250, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(25, 80, 250, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 270, 300, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setGeometry(QtCore.QRect(25, 30, 250, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 370, 300, 130))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_5.setGeometry(QtCore.QRect(25, 30, 250, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_6.setGeometry(QtCore.QRect(25, 80, 250, 30))
        self.pushButton_6.setObjectName("pushButton_6")
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 520, 300, 180))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_9.setGeometry(QtCore.QRect(25, 30, 250, 30))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_10.setGeometry(QtCore.QRect(25, 80, 250, 30))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_11.setGeometry(QtCore.QRect(25, 130, 250, 30))
        self.pushButton_11.setObjectName("pushButton_11")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "1. Background Subtraction"))
        self.pushButton.setText(_translate("Form", "1.1 Background Subtraction"))
        self.groupBox_2.setTitle(_translate("Form", "2. Optical flow"))
        self.pushButton_2.setText(_translate("Form", "2.1 Preprocessing"))
        self.pushButton_3.setText(_translate("Form", "2.2 Video tracking"))
        self.groupBox_3.setTitle(_translate("Form", "3. Perspective Transform"))
        self.pushButton_4.setText(_translate("Form", "3.1 Perspective Transform"))
        self.groupBox_4.setTitle(_translate("Form", "4. PCA"))
        self.pushButton_5.setText(_translate("Form", "4.1 Image Reconstruction"))
        self.pushButton_6.setText(_translate("Form", "4.2 Compute the Reconstruction Error"))
        self.groupBox_5.setTitle(_translate("Form", "5. cats/dogs classificarion using ResNet50"))
        self.pushButton_9.setText(_translate("Form", "5.2 Show the TensorBoard"))
        self.pushButton_10.setText(_translate("Form", "5.3 Test"))
        self.pushButton_11.setText(_translate("Form", "5.3 Random-Erasing"))
